package org.swasth.hcx.exception;

public enum ErrorCodes {
    ERR_INVALID_PARTICIPANT_DETAILS,
    ERR_SERVICE_UNAVAILABLE,
    INTERNAL_SERVER_ERROR,
    SERVER_ERR_GATEWAY_TIMEOUT,
    ERR_INVALID_SEARCH,
    ERR_INVALID_CORRELATION_ID,
    ERR_INVALID_WORKFLOW_ID,
    ERR_INVALID_PAYLOAD,
    ERR_INVALID_ENCRYPTION,
    ERR_WRONG_DOMAIN_PAYLOAD,
    ERR_INVALID_DOMAIN_PAYLOAD,
    ERR_SENDER_NOT_SUPPORTED,
    ERR_DOMAIN_PROCESSING,
    ERR_SENDING_OTP;

}
